### ISSUE TITLE
is there an F-droid version ?

### ISSUE THREAD

**Issue by luffah** [Julien-Blanc-tgcm/LAttestation#2]
sorry, not really an issue.

is there an F-droid version ? or a raw javascript/html source ?

**Comment by Julien-Blanc-tgcm** [comment]
No, sorry. PDF generation is using libpoppler, the app actually bundle sfos version, and the interface is using sailfish os specific qml components. It can be ported to android, but that's a lot of work, which i'm not interested in doing (i don't use android).

I think, however, that there are already similar programs in f-droid.
